(()=>{
'use strict';
const c=document.querySelector('#c'),g=c.getContext('2d'),W=c.width,H=c.height,PI=Math.PI,STEP=1/120,MAX_STEPS=8,SUMMIT=540-7770;
const K={},R=['#ff496d','#ff8b3d','#ffd84a','#59dd79','#4ecbff','#7377ff','#c769ff'];
let A=null,seed=0x13c0ffee,run=0,mode='title',cam=0,storm=770,best=0,score=0,bonus=0,peak=0,combo=0,flash=0,spectrum=0,last=0,acc=0,beat=.3,simSteps=0,droppedFrames=0,suspended=false,platforms=[],particles=[],genY=0,genX=440,summitMade=0;
const p={x:480,y:500,px:480,py:500,vx:0,vy:0,r:14,ground:null,hook:null,hookReady:true,spentY:1e9,clean:0,trail:[]};
try{best=+localStorage.uaBest||0}catch{}
const save=()=>{try{localStorage.uaBest=best}catch{}};
const rng=()=>((seed^=seed<<13,seed^=seed>>>17,seed^=seed<<5),(seed>>>0)/4294967296),clamp=(v,a,b)=>v<a?a:v>b?b:v;
const snd=(f,d=.05,v=.025)=>{try{A||(A=new AudioContext);const o=A.createOscillator(),q=A.createGain();o.frequency.value=f;q.gain.value=v;o.connect(q).connect(A.destination);o.start();q.gain.exponentialRampToValueAtTime(.0001,A.currentTime+d);o.stop(A.currentTime+d)}catch{}};
function arcY(a,x){const t=clamp((x-a.x)/a.w,0,1);return a.y-Math.sin(t*PI)*a.h}
function addPlatform(y,x,w,h=24,b=0){const a={x,y,w,h,b,used:0,hit:0,ax:x+w*(.35+rng()*.3),ay:y-70-rng()*25};platforms.push(a);return a}
function generate(toY){while(genY>toY&&genY>SUMMIT+130){const d=clamp((15-genY)/7115,0,1);genY-=68+rng()*(45+d*35);const w=165-d*25+rng()*(145-d*55);genX=clamp(genX+(rng()-.5)*(290+d*150),28,W-w-28);addPlatform(genY,genX,w,18+rng()*18);if(genY<0&&rng()<.2+d*.2){const bw=115-d*15+rng()*(85-d*25),bx=clamp(genX+(rng()<.5?-1:1)*(210+rng()*150),28,W-bw-28),by=genY-28-rng()*48;addPlatform(by,bx,bw,14+rng()*12,1)}}if(!summitMade&&genY<=SUMMIT+130){addPlatform(SUMMIT+10,310,340,42,2);summitMade=1}}
function reset(fresh=true){seed=fresh?(0x13c0ffee+run++*2654435761)>>>0:0x13c0ffee;platforms=[];particles=[];const s=addPlatform(540,310,340,22),guide=[[450,390,260],[350,150,240],[245,430,230],[130,190,230],[15,440,210]];for(const a of guide)addPlatform(...a);genY=15;genX=440;summitMade=0;generate(-2200);Object.assign(p,{x:480,y:500,px:480,py:500,vx:0,vy:0,ground:s,hook:null,hookReady:true,spentY:1e9,clean:0,trail:[]});cam=0;storm=770;score=bonus=peak=combo=flash=spectrum=0;beat=.3;acc=0;simSteps=0;droppedFrames=0;suspended=false;last=performance.now();mode='playing';snd(330,.06,.02)}
function nearestHook(){let b=null,bd=1e9;for(const a of platforms){if(a.used||a===p.ground)continue;const dx=a.ax-p.x,dy=a.ay-p.y,d=Math.hypot(dx,dy);if(d<290&&d<bd&&dy<130){b=a;bd=d}}return b}
const cleanWindow=()=>p.hook&&p.hook.age>.15&&p.hook.age<.78&&Math.abs(p.vx)>235;
function hook(){if(mode!=='playing'||suspended||p.hook||!p.hookReady)return;const a=nearestHook();if(!a)return;p.hook={a,age:0,rope:Math.max(105,Math.hypot(a.ax-p.x,a.ay-p.y)*.84)};p.hookReady=false;p.clean=0;p.spentY=p.ground?p.ground.y:p.y;a.used=1;snd(660,.04,.018);burst(a.ax,a.ay,8,1)}
function release(){if(!p.hook)return;const clean=cleanWindow();p.clean=clean?1:0;if(!clean)combo=Math.max(0,combo-1);p.vx*=1.06;p.vy*=1.03;p.hook=null}
function cancelHook(){if(!p.hook)return false;p.hook=null;p.clean=0;return true}
function suspend(){for(const k in K)K[k]=0;if(mode==='playing'){cancelHook();suspended=true}acc=0;last=performance.now()}
function resume(){acc=0;last=performance.now();if(!document.hidden)suspended=false}
function burst(x,y,n,k){for(let i=0;i<n;i++)particles.push({x,y,vx:(rng()-.5)*180*k,vy:(rng()-.5)*180*k,t:.35+rng()*.45,col:R[(combo+i)%7]})}
function jump(){if(mode==='title'||mode==='gameover'||mode==='won'){reset(true);return}if(!suspended&&p.ground){p.vy=-470;p.ground=null;snd(420,.05,.018)}}
function land(a){const higher=a.y<p.spentY-18;p.ground=a;p.vy=0;p.y=arcY(a,p.x)-p.r;if(a.b===1&&!a.hit){a.hit=1;bonus+=90;snd(760,.04,.018);burst(p.x,p.y,7,1.4)}if(!p.hookReady&&higher){p.hookReady=true;p.spentY=a.y;snd(520,.025,.012);if(p.clean){combo++;bonus+=combo*45;flash=.2;snd(820+combo*72,.08,.025);burst(p.x,p.y,10+combo,2);if(combo>=7){combo=0;spectrum=1.25;storm+=150;bonus+=777;snd(1320,.18,.035);burst(p.x,p.y,36,3)}}}else if(p.clean)combo=Math.max(0,combo-1);p.clean=0;burst(p.x,p.y+p.r,4,1)}
function update(dt){if(mode!=='playing'||suspended)return;p.px=p.x;p.py=p.y;const dir=(K.ArrowRight||K.KeyD?1:0)-(K.ArrowLeft||K.KeyA?1:0);p.vx+=dir*900*dt;if(!dir)p.vx*=Math.pow(.018,dt);p.vx=clamp(p.vx,-350,350);if(!p.ground)p.vy+=1040*dt;
 if(p.hook){const h=p.hook,a=h.a;h.age+=dt;const dx=a.ax-p.x,dy=a.ay-p.y,d=Math.hypot(dx,dy)||1;if(d>h.rope){const pull=(d-h.rope)*18+620;p.vx+=dx/d*pull*dt;p.vy+=dy/d*pull*dt}p.vx+=dir*360*dt;p.vx=clamp(p.vx,-470,470);p.vy=clamp(p.vy,-650,650)}
 p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<12){p.x=12;p.vx=Math.abs(p.vx)*.7}if(p.x>W-12){p.x=W-12;p.vx=-Math.abs(p.vx)*.7}
 if(p.ground){const a=p.ground;if(p.x>=a.x-3&&p.x<=a.x+a.w+3){p.y=arcY(a,p.x)-p.r;p.vy=0}else p.ground=null}
 if(!p.ground&&p.vy>=0){const oldFoot=p.py+p.r,newFoot=p.y+p.r;let hit=null,hy=1e9;for(const a of platforms){if(p.x<a.x-3||p.x>a.x+a.w+3)continue;const y=arcY(a,p.x);if(oldFoot<=y+5&&newFoot>=y-3&&y<hy){hit=a;hy=y}}if(hit)land(hit)}
 const target=p.y-350;cam+=(target-cam)*Math.min(1,dt*4.8);generate(p.y-2100);platforms=platforms.filter(a=>a===p.ground||a===p.hook?.a||a.y-cam<H+260);storm-=dt*(22+Math.min(50,Math.max(0,(540-p.y)*.013)));peak=Math.max(peak,540-p.y);score=Math.floor(peak*.65)+bonus;if(p.ground?.b===2){mode='won';best=Math.max(best,score);save();flash=1;snd(1040,.4,.04);burst(p.x,p.y,50,4)}else if(p.y>storm){mode='gameover';best=Math.max(best,score);save();snd(130,.25,.035)}
 if(A&&(beat-=dt)<=0){beat=.46;snd(110*Math.pow(2,((combo+2)%7)/12),.04,.006)}p.trail.push({x:p.x,y:p.y,t:.65,col:R[(combo+run)%7]});if(p.trail.length>30)p.trail.shift();for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=220*dt;q.t-=dt}particles=particles.filter(q=>q.t>0);for(const q of p.trail)q.t-=dt;p.trail=p.trail.filter(q=>q.t>0);flash=Math.max(0,flash-dt);spectrum=Math.max(0,spectrum-dt)}
function rainbow(a){const y=a.y-cam,life=clamp((storm-a.y+150)/220,0,1);g.globalAlpha=.15+.85*life;for(let i=0;i<7;i++){g.strokeStyle=R[i];g.lineWidth=a.b===2?6:a.b?3.3:4.3;g.beginPath();g.moveTo(a.x,y+i*4);g.quadraticCurveTo(a.x+a.w/2,y-a.h*1.35+i*4,a.x+a.w,y+i*4);g.stroke()}g.globalAlpha=1;if(!a.used){const x=a.ax,sy=a.ay-cam;g.fillStyle=a.b===1?'#ffe87c':'#fff';g.beginPath();for(let i=0;i<8;i++){const r=i%2?3:8,an=i*PI/4-PI/2;g.lineTo(x+Math.cos(an)*r,sy+Math.sin(an)*r)}g.fill()}if(a.b===1&&!a.hit){g.fillStyle='#fff8';g.font='700 11px system-ui';g.textAlign='center';g.fillText('+90',a.x+a.w/2,y-a.h-12)}if(a.b===2){g.fillStyle='#fff';g.font='900 13px system-ui';g.textAlign='center';g.fillText('777m',a.x+a.w/2,y-a.h-18)}}
function unicorn(){const x=p.x,y=p.y-cam,tilt=clamp(p.vx/800,-.3,.3),bob=p.ground?Math.sin(last*.018)*1.5:0;g.save();g.translate(x,y+bob);g.rotate(tilt);for(const q of p.trail){g.globalAlpha=q.t*.38;g.strokeStyle=q.col;g.lineWidth=4;g.beginPath();g.moveTo(-8+(q.x-p.x),8+(q.y-p.y));g.lineTo(-34+(q.x-p.x),15+(q.y-p.y));g.stroke()}g.globalAlpha=1;g.fillStyle='#fff';g.beginPath();g.ellipse(0,0,18,11,0,0,PI*2);g.fill();g.beginPath();g.arc(17,-9,9,0,PI*2);g.fill();g.strokeStyle='#e8ecff';g.lineWidth=4;for(const z of [-10,5]){g.beginPath();g.moveTo(z,8);g.lineTo(z-3,18+(p.ground?Math.sin(last*.025+z)*2:0));g.stroke()}g.strokeStyle=R[combo%7];g.lineWidth=5;g.beginPath();g.moveTo(-16,-3);g.quadraticCurveTo(-29,-15,-34,5);g.stroke();g.fillStyle=p.hookReady?'#ffd95a':'#8b91aa';g.beginPath();g.moveTo(20,-17);g.lineTo(28,-33);g.lineTo(24,-14);g.fill();g.fillStyle='#2c3262';g.beginPath();g.arc(20,-10,1.8,0,PI*2);g.fill();g.restore()}
function draw(){const sky=g.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#182653');sky.addColorStop(.58,'#477fc2');sky.addColorStop(1,'#f5b8d5');g.fillStyle=sky;g.fillRect(0,0,W,H);g.globalAlpha=.22;g.fillStyle='#fff';for(let i=0;i<45;i++){const x=i*197%W,y=(i*113+cam*.08)%H;g.fillRect(x,y,2,2)}g.globalAlpha=1;
 for(const a of platforms)if(a.y-cam>-120&&a.y-cam<H+120)rainbow(a);for(const q of particles){g.globalAlpha=Math.max(0,q.t*1.5);g.fillStyle=q.col;g.fillRect(q.x-2,q.y-cam-2,4,4)}g.globalAlpha=1;
 const target=mode==='playing'&&!p.hook&&!suspended&&p.hookReady?nearestHook():null;if(target){const sy=target.ay-cam,r=11+Math.sin(last*.012)*3;g.strokeStyle='#fff9';g.lineWidth=2;g.beginPath();g.arc(target.ax,sy,r,0,PI*2);g.stroke()}
 if(p.hook){const hot=cleanWindow(),a=p.hook.a;g.strokeStyle=hot?'#fff':'#fff8c8';g.lineWidth=hot?4:2.5;g.beginPath();g.moveTo(p.x,p.y-cam-15);g.lineTo(a.ax,a.ay-cam);g.stroke();g.strokeStyle=R[(combo+3)%7];g.lineWidth=1;g.stroke();if(hot){g.fillStyle='#fff';g.font='800 12px system-ui';g.textAlign='center';g.fillText('RELEASE!',a.ax,a.ay-cam-18)}}
 const sy=storm-cam;g.fillStyle='#34405b';g.globalAlpha=.86;g.fillRect(0,sy,W,H-sy+120);for(let x=-30;x<W+40;x+=55){g.beginPath();g.arc(x,sy+Math.sin(x*.04)*9,38,PI,0);g.fill()}g.globalAlpha=1;const danger=clamp(1-(storm-p.y)/270,0,.35);if(danger){g.fillStyle=`rgba(25,30,48,${danger})`;g.fillRect(0,0,W,H)}unicorn();
 const meters=Math.max(0,Math.floor((540-p.y)/10));g.fillStyle='#fff';g.font='700 18px system-ui';g.textAlign='left';g.fillText('↑ '+meters+'m / 777m',20,30);g.textAlign='right';g.fillText('BEST '+best,W-20,30);if(combo){g.textAlign='center';g.fillStyle=R[(combo-1)%7];g.fillText('SPECTRUM '+combo+'/7',W/2,31)}if(spectrum){g.textAlign='center';g.font='900 26px system-ui';g.fillStyle='#fff';g.fillText('SPECTRUM BURST!',W/2,H*.28)}if(!p.hookReady&&mode==='playing'){g.textAlign='center';g.font='600 12px system-ui';g.fillStyle='#ffffffaa';g.fillText('LAND HIGHER TO RELIGHT YOUR HORN',W/2,H-20)}
 if(mode!=='playing'){g.fillStyle='#11182dcc';g.fillRect(0,0,W,H);g.textAlign='center';g.fillStyle='#fff';g.font='900 54px system-ui';g.fillText('UNICORN ASCENDING',W/2,H*.32);g.font='700 18px system-ui';g.fillStyle='#ffe77a';if(mode==='title'){g.fillText('OUTCLIMB THE GREY · REACH 777m',W/2,H*.4);g.fillStyle='#fff';g.font='500 16px system-ui';g.fillText('A/D or ←/→ move   ·   SPACE jump   ·   hold SHIFT Horn Hook',W/2,H*.5);g.fillText('Release when the tether shines · land higher to recharge',W/2,H*.55);g.font='800 18px system-ui';g.fillText('SPACE TO ASCEND',W/2,H*.63)}else if(mode==='won'){g.fillText('YOU OUTRAN THE GREY!',W/2,H*.42);g.fillStyle='#fff';g.font='600 17px system-ui';g.fillText('SCORE '+score+'   ·   BEST '+best,W/2,H*.51);g.fillText('SPACE FOR ANOTHER SKY',W/2,H*.59)}else{g.fillText('THE GREY CAUGHT YOUR COLORS',W/2,H*.42);g.fillStyle='#fff';g.font='600 17px system-ui';g.fillText('HEIGHT '+meters+'m   ·   SCORE '+score+'   ·   BEST '+best,W/2,H*.51);g.fillText('SPACE TO RUN AGAIN',W/2,H*.59)}}if(flash){g.globalAlpha=flash;g.fillStyle='#fff';g.fillRect(0,0,W,H);g.globalAlpha=1}}
function frame(t){const dt=Math.min((t-last)/1000||0,.067);last=t;if(mode==='playing'&&!suspended){acc+=dt;let n=0;while(acc>=STEP&&n<MAX_STEPS){update(STEP);acc-=STEP;n++;simSteps++}if(n===MAX_STEPS&&acc>=STEP){acc=0;droppedFrames++}}draw();requestAnimationFrame(frame)}
addEventListener('keydown',e=>{K[e.code]=1;if(['Space','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();if(e.code==='Space'&&!e.repeat)jump();if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&!e.repeat)hook()});addEventListener('keyup',e=>{K[e.code]=0;if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&p.hook)release()});addEventListener('blur',suspend);addEventListener('focus',resume);document.addEventListener('visibilitychange',()=>document.hidden?suspend():resume());c.addEventListener('pointerdown',()=>c.focus());
window.UA={state:()=>({mode,x:p.x,y:p.y,vx:p.vx,vy:p.vy,ground:!!p.ground,hook:!!p.hook,hookReady:p.hookReady,platforms:platforms.length,score,best,combo,storm,suspended,fixedHz:120,simSteps,droppedFrames}),start:()=>reset(false),primeHook:()=>{if(mode!=='playing')reset(false);p.x=480;p.y=430;p.vx=250;p.vy=-30;p.ground=null;p.hookReady=true;p.clean=0;const a=nearestHook();return a&&{x:a.ax,y:a.ay}}};
generate(-2200);requestAnimationFrame(frame);
})();
