(()=>{
'use strict';
const c=document.querySelector('#c'),g=c.getContext('2d'),W=c.width,H=c.height,P=Math.PI,S=1/120,MS=8,K={},R=['#ff496d','#ff8b3d','#ffd84a','#59dd79','#4ecbff','#7377ff','#c769ff'];
let A,seed=0x13c0ffee,run=0,mode='title',cx=0,cy=0,grey=790,best=+(localStorage.uaBest||0),score=0,flow=0,flowT=0,flash=0,last=0,acc=0,steps=0,drops=0,suspended=false,plats=[],foes=[],shots=[],dust=[],shards=[],kills=0,boss=null,biome=0;
const p={x:0,y:500,px:0,py:500,vx:0,vy:0,r:14,ground:0,lastGround:0,hook:null,hookReady:1,face:1,dive:0,trail:[]};
const rnd=()=>((seed^=seed<<13,seed^=seed>>>17,seed^=seed<<5),(seed>>>0)/4294967296),clamp=(v,a,b)=>v<a?a:v>b?b:v;
const snd=(f,d=.05,v=.022,type='sine')=>{try{A||(A=new AudioContext);let o=A.createOscillator(),q=A.createGain();o.type=type;o.frequency.value=f;q.gain.value=v;o.connect(q).connect(A.destination);o.start();q.gain.exponentialRampToValueAtTime(.0001,A.currentTime+d);o.stop(A.currentTime+d)}catch{}};
const arc=(a,x)=>a.y-Math.sin(clamp((x-a.x)/a.w,0,1)*P)*a.h;
function plat(y,x,w,h=22,branch=0){let a={id:plats.length,x,y,w,h,branch,ax:x+w*(.3+rnd()*.4),ay:y-64-rnd()*38};plats.push(a);return a}
function foe(t,a,x=a.x+a.w*.5){let e={t,a:a?.id??-1,x,y:a?arc(a,x)-18:0,vx:0,vy:0,dir:rnd()<.5?-1:1,hp:t===4?5:1,phase:rnd()*6,cd:1+rnd()*1.5,dead:0,hit:0,homeX:x,homeY:a?arc(a,x)-110:0};foes.push(e);return e}
function world(){plats=[];foes=[];shots=[];shards=[];plat(540,-170,340,22);for(let n=1;n<38;n++){let y=540-n*(88+rnd()*18),center=Math.sin(n*.245)*1050+Math.sin(n*.105)*430,w=165+rnd()*120,a=plat(y,center-w/2,w,18+rnd()*18),side=n%3===0?(n%2?1:-1):rnd()<.32?(rnd()<.5?-1:1):0;if(side){let d=320+rnd()*260,bw=125+rnd()*125,b=plat(y+(rnd()-.5)*34,center+side*d-bw/2,bw,16+rnd()*16,1);shards.push({x:b.x+b.w*.5,y:arc(b,b.x+b.w*.5)-36,t:1});if(n>3&&rnd()<.72)foe(rnd()<.32?1:rnd()<.62?2:3,b)}if(n>2&&n<34&&rnd()<.78)foe(n<8?0:rnd()<.36?0:rnd()<.62?1:rnd()<.83?2:3,a)}let crown=plat(-3170,-190,380,34);boss=foe(4,crown,0);boss.y=arc(crown,0)-54}
function reset(newSeed=true){if(newSeed)seed=(0x13c0ffee+run++*2654435761)>>>0;world();Object.assign(p,{x:0,y:500,px:0,py:500,vx:0,vy:0,ground:0,lastGround:0,hook:null,hookReady:1,face:1,dive:0,trail:[]});cx=-W/2;cy=0;grey=790;score=flow=flowT=flash=kills=biome=0;dust=[];acc=steps=drops=0;suspended=false;last=performance.now();mode='playing';snd(330,.07,.025)}
function targets(){let out=[];for(const a of plats)out.push({o:a,k:0,x:a.ax,y:a.ay});for(const e of foes)if(!e.dead)out.push({o:e,k:1,x:e.x,y:e.y});return out}
function nearestHook(){let b=null,bd=1e9,rad=flowT?370:315;for(const q of targets()){let dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy);if(d<rad&&d<bd){b=q;bd=d}}return b}
function hook(){if(mode!=='playing'||suspended||p.hook||!p.hookReady)return;let q=nearestHook();if(!q)return;p.hook={...q,age:0,rope:Math.max(90,Math.hypot(q.x-p.x,q.y-p.y)*.8)};p.hookReady=0;snd(700,.04,.02);burst(q.x,q.y,8,1)}
function release(){if(!p.hook)return;let h=p.hook,clean=h.age>.13&&h.age<.8&&Math.hypot(p.vx,p.vy)>245;if(clean){flow=Math.min(7,flow+1);if(flow===7){flowT=5;flow=0;snd(1320,.18,.04,'triangle');grey+=70}else snd(820+flow*65,.07,.024);score+=50+flow*20;flash=.18;burst(p.x,p.y,12,2)}p.vx*=1.05;p.vy*=1.03;p.hook=null}
function cancelHook(){if(!p.hook)return false;p.hook=null;return true}
function suspend(){for(const k in K)K[k]=0;if(mode==='playing'){cancelHook();suspended=true}acc=0;last=performance.now()}
function resume(){acc=0;last=performance.now();if(!document.hidden)suspended=false}
function burst(x,y,n,k=1){for(let i=0;i<n;i++)dust.push({x,y,vx:(rnd()-.5)*190*k,vy:(rnd()-.5)*190*k,t:.25+rnd()*.45,col:R[(flow+i)%7]})}
function jump(){if(mode==='title'||mode==='dead'||mode==='win'){reset(mode!=='title');return}if(!suspended&&p.ground!=null){p.vy=-480;p.ground=null;p.dive=0;snd(430,.05,.018)}}
function dive(){if(mode==='playing'&&!suspended&&p.ground==null){p.dive=1;p.vy=Math.max(180,p.vy+80);snd(180,.035,.012,'square')}}
function land(a){let old=p.lastGround;p.ground=a.id;p.vy=0;p.y=arc(a,p.x)-p.r;p.dive=0;if(a.id!==old){p.hookReady=1;p.lastGround=a.id;snd(520,.025,.012)}burst(p.x,p.y+p.r,4)}
function hitPlayer(x,y,pow=240){let dx=p.x-x||1,d=Math.abs(dx)||1;p.vx=dx/d*pow;p.vy=-260;p.ground=null;p.dive=0;flow=0;flowT=0;flash=.22;snd(120,.12,.035,'sawtooth')}
function kill(e,kind){e.dead=1;kills++;score+=120+(flowT?100:0);grey+=42;p.hookReady=1;flow=Math.min(7,flow+1);burst(e.x,e.y,16,2);snd(960+flow*45,.07,.03,'triangle');if(kind===2){p.vy=-430;p.dive=0}else{p.vx*=1.08;p.vy*=.96}}
function combat(e){if(e.dead||e.hit>0)return;let dx=e.x-p.x,dy=e.y-p.y,rr=e.t===4?55:24;if(dx*dx+dy*dy>(p.r+rr)*(p.r+rr))return;let sp=Math.hypot(p.vx,p.vy),horn=p.face*p.vx>270&&Math.abs(p.vx)>Math.abs(p.vy)*.5,dv=p.dive&&p.vy>300&&p.y<e.y,behind=e.t!==2||(p.x-e.x)*e.dir<0,strong=flowT||sp>(e.t===4?430:340);if((horn||dv)&&strong&&behind){e.hp--;e.hit=.25;if(e.hp<=0)kill(e,dv?2:1);else{p.vx*=-.58;p.vy=-180;burst(e.x,e.y,12,2);snd(240,.08,.03,'square')}}else hitPlayer(e.x,e.y,e.t===3?330:230)}
function updateFoes(dt){for(const e of foes){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.phase+=dt;if(e.t===1){e.x=e.homeX+Math.sin(e.phase*.8)*55;e.y=e.homeY+Math.sin(e.phase*2)*24;e.cd-=dt;if(e.cd<0&&Math.hypot(p.x-e.x,p.y-e.y)<620){let d=Math.hypot(p.x-e.x,p.y-e.y)||1;shots.push({x:e.x,y:e.y,vx:(p.x-e.x)/d*155,vy:(p.y-e.y)/d*155,t:4});e.cd=1.8+rnd()}}else if(e.t===4){e.x=Math.sin(e.phase*.55)*150;e.y=e.homeY+Math.sin(e.phase*1.1)*55}else{let a=plats[e.a];if(!a)continue;let speed=e.t===0?55:e.t===2?28:42;if(e.t===3&&Math.abs(p.y-e.y)<70&&Math.abs(p.x-e.x)<420)speed=190;e.vx=e.dir*speed;e.x+=e.vx*dt;if(e.x<a.x+18||e.x>a.x+a.w-18)e.dir*=-1;e.y=arc(a,e.x)-18}combat(e)}for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt;if(s.t>0&&Math.hypot(s.x-p.x,s.y-p.y)<20){s.t=0;hitPlayer(s.x-s.vx,s.y-s.vy,190)}}shots=shots.filter(s=>s.t>0)}
function update(dt){if(mode!=='playing'||suspended)return;p.px=p.x;p.py=p.y;let dir=(K.ArrowRight||K.KeyD?1:0)-(K.ArrowLeft||K.KeyA?1:0);if(dir)p.face=dir;p.vx+=dir*(flowT?1120:930)*dt;if(!dir)p.vx*=Math.pow(.025,dt);p.vx=clamp(p.vx,-(flowT?520:390),flowT?520:390);p.vy+=(p.dive?1850:1050)*dt;if(p.hook){let h=p.hook,o=h.o;if(o.dead){p.hook=null}else{h.age+=dt;h.x=h.k?o.x:o.ax;h.y=h.k?o.y:o.ay;let dx=h.x-p.x,dy=h.y-p.y,d=Math.hypot(dx,dy)||1;if(h.k&&o.t===0){if(d>h.rope){let pull=(d-h.rope)*12+520;o.x-=dx/d*pull*dt;o.y-=dy/d*pull*dt}}else if(d>h.rope){let pull=(d-h.rope)*18+650;p.vx+=dx/d*pull*dt;p.vy+=dy/d*pull*dt}p.vx+=dir*340*dt;p.vx=clamp(p.vx,-590,590);p.vy=clamp(p.vy,-720,760)}}p.x+=p.vx*dt;p.y+=p.vy*dt;p.ground=null;if(p.vy>=0){let of=p.py+p.r,nf=p.y+p.r;for(const a of plats){if(p.x<a.x-4||p.x>a.x+a.w+4)continue;let y=arc(a,p.x);if(of<=y+5&&nf>=y-3){land(a);break}}}updateFoes(dt);for(const s of shards)if(s.t&&Math.hypot(s.x-p.x,s.y-p.y)<30){s.t=0;score+=180;grey+=70;p.hookReady=1;flow=Math.min(7,flow+1);burst(s.x,s.y,14,2);snd(1100,.1,.03,'triangle')}let tx=p.x+p.vx*.38-W/2,ty=p.y+p.vy*.12-H*.56;cx+=(tx-cx)*Math.min(1,dt*4);cy+=(ty-cy)*Math.min(1,dt*4);grey-=dt*(19+Math.max(0,Math.min(28,(-p.y)*.006)));if(flowT>0)flowT=Math.max(0,flowT-dt);score=Math.max(score,Math.floor((540-Math.min(540,p.y))*.45)+kills*90);biome=p.y<-2050?2:p.y<-850?1:0;if(p.y>grey){mode='dead';best=Math.max(best,score);localStorage.uaBest=best;snd(110,.28,.04,'sawtooth')}if(boss?.dead){mode='win';best=Math.max(best,score+1000);localStorage.uaBest=best;snd(1560,.35,.05,'triangle')}p.trail.push({x:p.x,y:p.y,t:.55,col:R[(flow+kills)%7]});if(p.trail.length>34)p.trail.shift();for(const q of dust){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=220*dt;q.t-=dt}dust=dust.filter(q=>q.t>0);for(const q of p.trail)q.t-=dt;p.trail=p.trail.filter(q=>q.t>0);flash=Math.max(0,flash-dt)}
function rainbow(a){let x=a.x-cx,y=a.y-cy,fade=clamp((grey-a.y)/220,0,1);for(let i=0;i<7;i++){g.globalAlpha=.18+.82*fade;g.strokeStyle=R[i];g.lineWidth=4.2;g.beginPath();g.moveTo(x,y+i*4);g.quadraticCurveTo(x+a.w/2,y-a.h*1.35+i*4,x+a.w,y+i*4);g.stroke()}g.globalAlpha=1;let ax=a.ax-cx,ay=a.ay-cy;g.fillStyle='#fff';g.beginPath();for(let i=0;i<8;i++){let r=i%2?3:8,z=i*P/4-P/2;g.lineTo(ax+Math.cos(z)*r,ay+Math.sin(z)*r)}g.fill()}
function drawFoe(e){if(e.dead)return;let x=e.x-cx,y=e.y-cy;if(x<-90||x>W+90||y<-90||y>H+90)return;g.save();g.translate(x,y);if(e.t===0){g.fillStyle='#687083';g.beginPath();g.arc(0,0,15,0,P*2);g.fill();g.fillStyle='#f8f8ff';g.fillRect(e.dir*7,-4,4,4)}else if(e.t===1){g.fillStyle='#536078';g.beginPath();g.arc(0,0,17,0,P*2);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(0,0,7,0,P*2);g.fill();g.fillStyle='#222';g.beginPath();g.arc((p.x>e.x?1:-1)*2,0,3,0,P*2);g.fill()}else if(e.t===2){g.scale(e.dir,1);g.fillStyle='#7c6e9c';g.fillRect(-15,-13,30,26);g.fillStyle='#dff6ff';g.beginPath();g.moveTo(14,-18);g.lineTo(29,0);g.lineTo(14,18);g.fill()}else if(e.t===3){g.scale(e.dir,1);g.fillStyle='#596273';g.beginPath();g.ellipse(0,0,25,16,0,0,P*2);g.fill();g.strokeStyle='#e2eaff';g.lineWidth=4;g.beginPath();g.moveTo(15,-8);g.lineTo(31,-17);g.moveTo(15,8);g.lineTo(31,17);g.stroke()}else{g.fillStyle='#252b42';g.beginPath();g.arc(0,0,48,0,P*2);g.fill();g.strokeStyle=R[(5-e.hp)%7];g.lineWidth=7;g.beginPath();g.arc(0,0,33,e.phase,e.phase+4.7);g.stroke();g.fillStyle='#fff';g.font='700 11px system-ui';g.textAlign='center';g.fillText('COLOR EATER',0,-58)}g.restore()}
function unicorn(){let x=p.x-cx,y=p.y-cy,t=clamp(p.vx/850,-.3,.3);g.save();g.translate(x,y);g.rotate(t);g.scale(p.face,1);for(const q of p.trail){g.globalAlpha=q.t*.45;g.strokeStyle=q.col;g.lineWidth=4;g.beginPath();g.moveTo(-8+p.face*(q.x-p.x),8+q.y-p.y);g.lineTo(-35+p.face*(q.x-p.x),14+q.y-p.y);g.stroke()}g.globalAlpha=1;g.fillStyle=flowT?'#fffde0':'#fff';g.beginPath();g.ellipse(0,0,18,p.dive?8:11,0,0,P*2);g.fill();g.beginPath();g.arc(17,-9,9,0,P*2);g.fill();g.strokeStyle='#e8ecff';g.lineWidth=4;for(const z of [-10,5]){g.beginPath();g.moveTo(z,8);g.lineTo(z-3,18);g.stroke()}g.strokeStyle=R[(flow+kills)%7];g.lineWidth=5;g.beginPath();g.moveTo(-16,-3);g.quadraticCurveTo(-29,-15,-34,5);g.stroke();g.fillStyle='#ffe45e';g.beginPath();g.moveTo(20,-17);g.lineTo(31,-35);g.lineTo(24,-14);g.fill();g.fillStyle='#283057';g.beginPath();g.arc(20,-10,1.8,0,P*2);g.fill();g.restore()}
function draw(){let sky=[['#182653','#477fc2','#f4b7d6'],['#141c45','#5854a6','#ef8ed0'],['#0b1732','#314e82','#7fc9e8']][biome],gr=g.createLinearGradient(0,0,0,H);gr.addColorStop(0,sky[0]);gr.addColorStop(.58,sky[1]);gr.addColorStop(1,sky[2]);g.fillStyle=gr;g.fillRect(0,0,W,H);g.globalAlpha=.18;g.fillStyle='#fff';for(let i=0;i<55;i++){let x=((i*197-cx*.08)%W+W)%W,y=((i*113-cy*.05)%H+H)%H;g.fillRect(x,y,2,2)}g.globalAlpha=1;for(const a of plats)if(a.x+a.w-cx>-120&&a.x-cx<W+120&&a.y-cy>-130&&a.y-cy<H+130)rainbow(a);for(const s of shards)if(s.t){let x=s.x-cx,y=s.y-cy;g.fillStyle=R[((s.x+s.y|0)%7+7)%7];g.beginPath();g.moveTo(x,y-10);g.lineTo(x+8,y);g.lineTo(x,y+10);g.lineTo(x-8,y);g.fill()}for(const s of shots){g.fillStyle='#c9ceda';g.beginPath();g.arc(s.x-cx,s.y-cy,6,0,P*2);g.fill()}for(const e of foes)drawFoe(e);for(const q of dust){g.globalAlpha=Math.max(0,q.t*1.8);g.fillStyle=q.col;g.fillRect(q.x-cx-2,q.y-cy-2,4,4)}g.globalAlpha=1;if(p.hook){let h=p.hook;g.strokeStyle='#fff8c8';g.lineWidth=3;g.beginPath();g.moveTo(p.x-cx,p.y-cy-14);g.lineTo((h.k?h.o.x:h.o.ax)-cx,(h.k?h.o.y:h.o.ay)-cy);g.stroke();g.strokeStyle=R[(flow+3)%7];g.lineWidth=1;g.stroke()}let gy=grey-cy;g.fillStyle='#30384e';g.globalAlpha=.88;g.fillRect(0,gy,W,H-gy+120);for(let x=-30;x<W+50;x+=55){g.beginPath();g.arc(x,gy+Math.sin((x+cx)*.04)*9,38,P,0);g.fill()}g.globalAlpha=1;unicorn();g.fillStyle='#fff';g.font='700 17px system-ui';g.textAlign='left';g.fillText('↑ '+Math.max(0,Math.floor((540-p.y)/10))+'m',18,28);g.fillText('✦ '+score,18,51);g.textAlign='right';g.fillText('KILLS '+kills,W-18,28);g.fillText('BEST '+best,W-18,51);g.textAlign='center';g.fillStyle=flowT?'#fff59b':R[Math.max(0,flow-1)%7];g.fillText(flowT?'PRISMATIC FLOW '+flowT.toFixed(1):'SPECTRUM '+flow+'/7',W/2,29);if(p.y>260){g.font='600 13px system-ui';g.fillStyle='#ffffffd0';g.fillText('A/D MOVE  •  SPACE JUMP  •  SHIFT HORN HOOK  •  ↓ COMET DIVE',W/2,H-22)}else if(p.y>40){g.font='600 13px system-ui';g.fillStyle='#ffffffcc';g.fillText('SPEED IS DAMAGE  •  KILLS RECHARGE THE HORN',W/2,H-22)}if(mode!=='playing'){g.fillStyle='#10162bd4';g.fillRect(0,0,W,H);g.textAlign='center';g.fillStyle='#fff';g.font='900 50px system-ui';g.fillText(mode==='win'?'ASCENDED':'UNICORN ASCENDING',W/2,H*.34);g.font='700 18px system-ui';g.fillStyle='#ffe77a';g.fillText(mode==='win'?'THE SPECTRUM LIVES':'PRISMWILD',W/2,H*.41);g.fillStyle='#fff';g.font='500 16px system-ui';if(mode==='title'){g.fillText('EXPLORE THE SKY • BUILD VELOCITY • BREAK THE GREY',W/2,H*.5);g.fillText('SPACE TO ASCEND',W/2,H*.58)}else{g.fillText('SCORE '+score+'   •   KILLS '+kills+'   •   BEST '+best,W/2,H*.5);g.fillText('SPACE TO RUN AGAIN',W/2,H*.58)}}if(flash){g.globalAlpha=flash;g.fillStyle='#fff';g.fillRect(0,0,W,H);g.globalAlpha=1}}
function frame(t){let dt=Math.min((t-last)/1000||0,.067);last=t;if(mode==='playing'&&!suspended){acc+=dt;let n=0;while(acc>=S&&n<MS){update(S);acc-=S;n++;steps++}if(n===MS&&acc>=S){acc=0;drops++}}draw();requestAnimationFrame(frame)}
addEventListener('keydown',e=>{K[e.code]=1;if(['Space','ArrowLeft','ArrowRight','ArrowDown','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();if(e.code==='Space'&&!e.repeat)jump();if((e.code==='ArrowDown'||e.code==='KeyS')&&!e.repeat)dive();if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&!e.repeat)hook()});addEventListener('keyup',e=>{K[e.code]=0;if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&p.hook)release()});addEventListener('blur',suspend);addEventListener('focus',resume);document.addEventListener('visibilitychange',()=>document.hidden?suspend():resume());c.addEventListener('pointerdown',()=>c.focus());
window.UA={state:()=>({mode,x:p.x,y:p.y,vx:p.vx,vy:p.vy,camX:cx,camY:cy,hook:!!p.hook,hookReady:!!p.hookReady,platforms:plats.length,enemies:foes.filter(e=>!e.dead).length,kills,score,best,flow,flowT,grey,suspended,fixedHz:120,simSteps:steps,droppedFrames:drops}),start:()=>reset(false),primeHook:()=>{if(mode!=='playing')reset(false);let a=plats[1];p.x=a.x+a.w/2;p.y=a.y+40;p.vx=260;p.vy=-20;p.ground=null;p.hookReady=1;let q=nearestHook();return q&&{x:q.x,y:q.y}},primeCombat:()=>{if(mode!=='playing')reset(false);let e=foes.find(e=>!e.dead&&e.t===0);p.x=e.x-70;p.y=e.y;p.py=p.y;p.vx=480;p.vy=0;p.face=1;p.ground=null;p.hook=null;p.hookReady=1;return{x:e.x,y:e.y,kills}},world:()=>({minX:Math.min(...plats.map(a=>a.x)),maxX:Math.max(...plats.map(a=>a.x+a.w)),topY:Math.min(...plats.map(a=>a.y))})};
world();requestAnimationFrame(frame);
})();